server:
  port: 9091
  max-http-header-size: 1000000

# SPRING CONFIG
spring:

  #  DATASOURCE MARIADB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.20.33:3306/mar_platform?createDatabaseIfNotExist=true&autoReconnect=true&UseUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Tpc@123456

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # KAFKA CONFIGURATION
  kafka:
    listener:
      missing-topics-fatal: false
    # CONFIG CONSUMER
    consumer:
      group-id: sms_service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: 192.168.20.32:9092
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    # CONFIG PRODUCER
    producer:
      bootstrap-servers: 192.168.20.32:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer

  boot:
    admin:
      client:
        url: http://admin-server:9090
        username: admin
        password: admin
      notify:
        mail:
          to:

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

#Eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetchRegistry: true
    instance:
      preferIpAddress: false

sms-service:
  topics:
    default-topic: sms-infor
    sms-infor: sms-infor,err-sms-infor

adapter-service:
  authorization-key: Authorization
  authorization-value: eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFMyNTYifQ.eyJqdGkiOiIxIiwiaWF0IjoxNjAyMjE1NDMwLCJzdWIiOiI4NWM2ZGMyYy0zMzU2LTRhNmQtYTJlZS02NWEzZDJkYTViZTMiLCJpc3MiOiJBRE1JTiAzVCIsInVzZXJfaWQiOjEsInBlcm1pc3Npb25zIjoie1wiZ2VuZXJhbFBlcm1pc3Npb25zXCI6W1wiVVNFUl9HRVRfQUxMXCIsXCJVU0VSX0RFTEVURVwiLFwiVVNFUl9BRERcIixcIlVTRVJfVVBEQVRFXCIsXCJVU0VSX0dFVF9CWV9JRFwiLFwiVVNFUl9BRERfUk9MRVNcIixcIlVTRVJfVVBEQVRFX1JPTEVTXCIsXCJVU0VSX0RFTEVURV9ST0xFU1wiLFwiVVNFUl9HRVRfUk9MRVNcIixcIlVTRVJfRU5BQkxFXCIsXCJVU0VSX0RJU0FCTEVcIixcIlVTRVJfVVBEQVRFX1NUQVRVU19MSVNUXCIsXCJVU0VSX0RFTEVURV9MSVNUXCIsXCJVU0VSX0dFVF9BTExfUk9MRV9BU1NJR05FRFwiLFwiVVNFUl9HRVRfQUxMX0dST1VQX0hBU19NRU1CRVJcIixcIlVTRVJfR0VUX0FMTF9VU0VSX0FORF9HUk9VUFwiLFwiVVNFUl9HRVRfTElTVF9TVEFUVVNcIixcIlVTRVJfVVBEQVRFX1NUQVRVU19BTExcIixcIlVTRVJfREVMRVRFX0FMTFwiLFwiVVNFUl9HRVRfQUxMX1BFUk1JU1NJT05cIixcIkdST1VQX1VTRVJfQUREXCIsXCJHUk9VUF9VU0VSX1VQREFURVwiLFwiR1JPVVBfVVNFUl9ERUxFVEVcIixcIkdST1VQX1VTRVJfR0VUX0JZX0lEXCIsXCJHUk9VUF9VU0VSX0dFVF9BTExcIixcIkdST1VQX1VTRVJfQUREX1VTRVJcIixcIkdST1VQX1VTRVJfREVMRVRFX1VTRVJcIixcIkdST1VQX1VTRVJfVVBEQVRFX1JPTEVcIixcIkdST1VQX1VTRVJfREVMRVRFX1JPTEVcIixcIkdST1VQX1VTRVJfR0VUX0FMTF9VU0VSXCIsXCJHUk9VUF9VU0VSX0dFVF9BTExfUk9MRVwiLFwiR1JPVVBfVVNFUl9BRERfUk9MRVwiLFwiR1JPVVBfVVNFUl9VUERBVEVfVVNFUlwiLFwiR1JPVVBfVVNFUl9HRVRfQUxMX1JPTEVfQVNTSUdORURcIixcIkdST1VQX1VTRVJfR0VUX0FMTF9OT19QQUdJTkdcIixcIlJPTEVfQUREXCIsXCJST0xFX1VQREFURVwiLFwiUk9MRV9ERUxFVEVcIixcIlJPTEVfR0VUX0FMTFwiLFwiUk9MRV9HRVRfQllfSURcIixcIlJPTEVfR0VUX0FMTF9QRVJNSVNTSU9OXCIsXCJST0xFX0dFVF9CWV9UWVBFXCIsXCJST0xFX0dFVF9BTExfTk9fUEFHSU5HXCIsXCJTWVNURU1fQ09ORklHX0dFVF9BTExfQllfS0VZXCIsXCJTWVNURU1fQ09ORklHX0FERFwiLFwiU1lTVEVNX0NPTkZJR19VUERBVEVcIixcIlNZU1RFTV9DT05GSUdfREVMRVRFXCIsXCJTWVNURU1fQ09ORklHX0dFVF9CWV9JRFwiLFwiU1lTVEVNX0NPTkZJR19HRVRfQUxMXCIsXCJTWVNURU1fQ09ORklHX0dFVF9BTExfS0VZXCIsXCJGSUVMRF9DT05GSUdfQUREXCIsXCJGSUVMRF9DT05GSUdfVVBEQVRFXCIsXCJGSUVMRF9DT05GSUdfREVMRVRFXCIsXCJGSUVMRF9DT05GSUdfR0VUX0FMTFwiLFwiRklFTERfQ09ORklHX0dFVF9CWV9JRFwiLFwiQ09OVEFDVF9HRVRfQUxMXCIsXCJDT05UQUNUX0VYUE9SVFwiLFwiQ09OVEFDVF9ERVRBSUxcIixcIlNMSU5LX0FERFwiLFwiU0xJTktfQ09OVkVSVF9MSU5LXCIsXCJDSEVDS19MSU5LX0FWQUlMQUJMRVwiLFwiU0xJTktfR0VUX1NPVVJDRVwiLFwiU0xJTktfR0VUX0FMTFwiLFwiU0xJTktfUkVQT1JUU1wiLFwiU0xJTktfRVhURU5TSU9OX0xJTktcIixcIkNBTVBBSUdOX0FERFwiLFwiQ0FNUEFJR05fVVBEQVRFXCIsXCJDQU1QQUlHTl9VUERBVEVfU1RBVFVTXCIsXCJDQU1QQUlHTl9ERUxFVEVcIixcIkNBTVBBSUdOX0dFVF9BTExcIixcIkNBTVBBSUdOX0dFVF9CWV9JRFwiLFwiQ0FNUEFJR05fR0VUX1NPVVJDRVNcIixcIkNBTVBBSUdOX1VQREFURV9TT1VSQ0VcIixcIkNBTVBBSUdOX0FERF9VU0VSXCIsXCJDQU1QQUlHTl9ERUxFVEVfVVNFUlwiLFwiQ0FNUEFJR05fVVBEQVRFX1BFUk1JU1NJT05cIixcIkNBTVBBSUdOX0dFVF9BTExfTk9fUEFHSU5HXCIsXCJDQU1QQUlHTl9HRVRfQUxMX0FTU0lHTkVEX1RPX1VTRVJcIixcIkNBTVBBSUdOX0dFVF9VU0VSU1wiLFwiQ0FNUEFJR05fR0VUX0FMTF9TT1VSQ0VcIixcIkNBTVBBSUdOX0dFVF9BTExfU1RBVFVTXCIsXCJDQU1QQUlHTl9SRU1PVkVfVVNFUl9BTExfQ0FNUEFJR05cIixcIlNPVVJDRV9BRERcIixcIlNPVVJDRV9VUERBVEVcIixcIlNPVVJDRV9ERUxFVEVcIixcIlNPVVJDRV9HRVRfQUxMXCIsXCJTT1VSQ0VfR0VUX0JZX0lEXCIsXCJTT1VSQ0VfR0VUX0FMTF9OT19QQUdJTkdcIixcIlNPVVJDRV9HRVRfQUxMX1NUQVRVU1wiLFwiTEFORElOR19QQUdFX0FERFwiLFwiTEFORElOR19QQUdFX1VQREFURVwiLFwiTEFORElOR19QQUdFX0RFTEVURVwiLFwiTEFORElOR19QQUdFX0dFVF9BTExcIixcIkxBTkRJTkdfUEFHRV9HRVRfQllfSURcIixcIkxBTkRJTkdfUEFHRV9HRVRfU1RBVFVTXCIsXCJMQU5ESU5HX1BBR0VfR0VUX0FMTF9OT19QQUdJTkdcIixcIlRSQUNLSU5HX1VSTF9BRERcIixcIlRSQUNLSU5HX1VSTF9VUERBVEVcIixcIlRSQUNLSU5HX1VSTF9ERUxFVEVcIixcIlRSQUNLSU5HX1VSTF9HRVRfQUxMXCIsXCJUUkFDS0lOR19VUkxfR0VUX0JZX0lEXCIsXCJUUkFDS0lOR19VUkxfQ0hBTkdFX1NUQVRVU1wiLFwiVFJBQ0tJTkdfVVJMX0dFVF9ERVRBSUxcIixcIlRSQUNLSU5HX1VSTF9HRVRfU1RBVFVTXCIsXCJUUkFDS0lOR19VUkxfR0VUX0FMTF9DQU1QQUlHTlwiLFwiREVWRUxPUEVSXCIsXCJDTElFTlRfQUREXCIsXCJDTElFTlRfR0VUX0FMTFwiLFwiQ0xJRU5UX0dFVF9CWV9JRFwiLFwiQ0xJRU5UX0RFTEVURVwiLFwiQ0xJRU5UX0NIQU5HRV9TVEFUVVNcIixcIkNMSUVOVF9BRERfSVBfV0hJVEVMSVNUXCIsXCJDTElFTlRfREVMRVRFX0lQX1dISVRFTElTVFwiLFwiQ0xJRU5UX0dFVF9MSVNUX0lQX1dISVRFTElTVFwiLFwiQ0xJRU5UX0dFVF9MSVNUX1RPS0VOXCIsXCJDTElFTlRfQVBQUk9WRV9UT0tFTlwiLFwiQ0xJRU5UX1VOX0FQUFJPVkVfVE9LRU5cIixcIkNMSUVOVF9ERUxFVEVfVE9LRU5cIixcIkNMSUVOVF9DSEFOR0VfU1RBVFVTX1RPS0VOXCIsXCJDTElFTlRfVVBEQVRFXCIsXCJVU0VSX0dFVF9BTExfVE9LRU5cIixcIkNMSUVOVF9HRVRfUkVGUkVTSF9UT0tFTlNfQllfQVBQX0lEXCIsXCJDTElFTlRfR0VUX0FDQ0VTU19UT0tFTlNfQllfQVBQX0lEXCIsXCJHRVRfU1RBVFVTX09GX0FDQ0VTU19UT0tFTlwiLFwiQ0xJRU5UX0dFVF9MSVNUX1JFUVVFU1RfTE9HXCIsXCJDTElFTlRfR0VUX1JFUVVFU1RfTE9HX0JZX0lEXCIsXCJDTElFTlRfQUREX1VTRVJcIixcIkNMSUVOVF9BRERfU0VSVklDRVwiLFwiQ0xJRU5UX0FERF9BUElcIixcIkNMSUVOVF9ERUxFVEVfQVBJXCIsXCJDTElFTlRfR0VUX1NFUlZJQ0VcIixcIkNMSUVOVF9HRVRfU0VSVklDRV9TVEFUVVNcIixcIkNMSUVOVF9HRVRfU0VSVklDRVNcIixcIkNMSUVOVF9TRVJWSUNFX0dFVF9BUElTXCIsXCJDTElFTlRfUEVORElOR19TRVJWSUNFXCIsXCJDTElFTlRfREVMRVRFX1NFUlZJQ0VcIixcIkNMSUVOVF9ERUxFVEVfVVNFUlwiLFwiQ0xJRU5UX0dFVF9VU0VSU1wiLFwiQ0xJRU5UX1VQREFURV9ST0xFX1VTRVJcIixcIkNMSUVOVF9VUERBVEVfU1RBVFVTX0FDQ0VTU19UT0tFTlwiLFwiRU1BSUxfQ09ORklHX0FERFwiLFwiRU1BSUxfQ09ORklHX0VESVRcIixcIkVNQUlMX0NPTkZJR19ERUxFVEVcIixcIkVNQUlMX0NPTkZJR19HRVRTXCIsXCJFTUFJTF9DT05GSUdfR0VUX0JZX0lEXCIsXCJFTUFJTF9QVUJMSVNIRVJfQUREXCIsXCJFTUFJTF9QVUJMSVNIRVJfRURJVFwiLFwiRU1BSUxfUFVCTElTSEVSX0RFTEVURVwiLFwiRU1BSUxfUFVCTElTSEVSX0dFVFNcIixcIkVNQUlMX1JFQ0VJVkVfRU1BSUxfRlJPTV9OT1RJRllfU0VSVklDRVwiLFwiU01TX0NPTkZJR19BRERcIixcIlNNU19DT05GSUdfRURJVFwiLFwiU01TX0NPTkZJR19ERUxFVEVcIixcIlNNU19DT05GSUdfR0VUU1wiLFwiU01TX0NPTkZJR19HRVRfQllfSURcIixcIlNNU19QVUJMSVNIRVJfQUREXCIsXCJTTVNfUFVCTElTSEVSX0VESVRcIixcIlNNU19QVUJMSVNIRVJfREVMRVRFXCIsXCJTTVNfUFVCTElTSEVSX0dFVFNcIixcIlNNU19SRUNFSVZFX1NNU19GUk9NX05PVElGWV9TRVJWSUNFXCIsXCJTRU5EX1NNU19UT19NT0JJRk9ORVwiLFwiVVBEQVRFX1NUQVRVU19ISVNUT1JZX05PVElGWVwiLFwiTk9USUZZX0hJU1RPUllfR0VUU1wiLFwiTk9USUZZX0hJU1RPUllfRVhQT1JUXCIsXCJOT1RJRllfSElTVE9SWV9HRVRfQllfSURcIixcIk5PVElGWV9ISVNUT1JZX0FERFwiXSxcInNwZWNpZmljUGVybWlzc2lvbnNcIjpbXX0iLCJuYW1lIjoiQURNSU4gM1QiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOiJCZWFyZXIiLCJlbWFpbCI6InNpbmhodkB0aGluaHRpZW50ZWNoLmNvbSIsImV4cCI6MTYwMjIyNTQzMH0.6-qK_REsT0V52ZXx1Z04Z9kF1jkJVyIykZ6OaSy2A5w
  url-sms: http://adapter-service:9090/send-sms

notify-service:
  url-update-status: http://notify-service:9090/status-history
