package com.ttt.mar.email.config;

public interface ServicePermissionCode {

  String EMAIL_CONFIG_ADD = "EMAIL_CONFIG_ADD";
  String EMAIL_CONFIG_EDIT = "EMAIL_CONFIG_EDIT";
  String EMAIL_CONFIG_DELETE = "EMAIL_CONFIG_DELETE";
  String EMAIL_CONFIG_GETS = "EMAIL_CONFIG_GETS";
  String EMAIL_CONFIG_GET_BY_ID = "EMAIL_CONFIG_GET_BY_ID";
  String EMAIL_PUBLISHER_ADD = "EMAIL_PUBLISHER_ADD";
  String EMAIL_PUBLISHER_EDIT = "EMAIL_PUBLISHER_EDIT";
  String EMAIL_PUBLISHER_DELETE = "EMAIL_PUBLISHER_DELETE";
  String EMAIL_PUBLISHER_GETS = "EMAIL_PUBLISHER_GETS";

  String EMAIL_RECEIVE_EMAIL_FROM_NOTIFY_SERVICE = "EMAIL_RECEIVE_EMAIL_FROM_NOTIFY_SERVICE";

}
