#CONFIG PORT
server:
  port: 9093
  max-http-header-size: 1000000

# SPRING CONFIG
spring:
  session:
    timeout: 100000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://root:example@192.168.20.44:27017/admin
      database: mar_data
      lead-collection: lead
      history-lead-collection: history_lead
      lead_status: lead_status
      lead-trash: lead_trash
      lead-file: lead_file
      lead-distribute-status-history: lead_distribute_status_history

  kafka:
    listener:
      missing-topics-fatal: false
    # CONFIG CONSUMER
    consumer:
      group-id: sms_service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: 192.168.20.44:9092
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    # CONFIG PRODUCERa
    producer:
      bootstrap-servers: 192.168.20.44:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  #  DATASOURCE MARIADB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.20.33:3306/core_platform?createDatabaseIfNotExist=false&autoReconnect=true&UseUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Tpc@123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true


schedule:
  campaign:
    expired: 0 30 11 ? * *
  project:
    expired: 0 30 11 ? * *
#Eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetchRegistry: true
    instance:
      preferIpAddress: true

mar:
  info:
    import-dir: import/
    export-dir: export/
    template: template/ImportLead_FileMau.xlsx

template:
  leads:
    config-file-download-name: template_download_lead.json
    config-file-name: template_leads.json


leadgen-service:
  kafka:
    default-topic: leadgen-kyc-dev-01
    confirm-info-topic: leadgen-kyc-dev,err-leadgen-kyc-dev
partner:
  kafka:
    default-topic: transfer_lead_dev-01