package com.ttt.mar.config.config;

public interface ServicePermissionCode {

  String SYSTEM_CONFIG_ADD = "SYSTEM_CONFIG_ADD";
  String SYSTEM_CONFIG_UPDATE = "SYSTEM_CONFIG_UPDATE";
  String SYSTEM_CONFIG_DELETE = "SYSTEM_CONFIG_DELETE";
  String SYSTEM_CONFIG_GET_BY_ID = "SYSTEM_CONFIG_GET_BY_ID";
  String SYSTEM_CONFIG_GET_ALL = "SYSTEM_CONFIG_GET_ALL";
  String FIELD_CONFIG_ADD = "FIELD_CONFIG_ADD";
  String FIELD_CONFIG_UPDATE = "FIELD_CONFIG_UPDATE";
  String FIELD_CONFIG_DELETE = "FIELD_CONFIG_DELETE";
  String FIELD_CONFIG_GET_ALL = "FIELD_CONFIG_GET_ALL";
  String FIELD_CONFIG_GET_BY_ID = "FIELD_CONFIG_GET_BY_ID";
  String GET_ALL_SYS_NAVIGATOR = "GET_ALL_SYS_NAVIGATOR";

}
