package com.ttt.mar.leads.config;

/**
 * @author bontk
 * @created_date 22/03/2021
 */

public interface ServicePermissionCode {

  String ADD_LEAD_SOURCE = "ADD_LEAD_SOURCE";
  String GET_LEAD_SOURCE_BY_ID = "GET_LEAD_SOURCE_BY_ID";
  String UPDATE_LEAD_SOURCE = "UPDATE_LEAD_SOURCE";
  String GET_ALL_LEAD_SOURCE = "GET_ALL_LEAD_SOURCE";
  String UPDATE_STATUS_LEAD_SOURCE = "UPDATE_STATUS_LEAD_SOURCE";
  String DELETE_LEAD_SOURCE = "DELETE_LEAD_SOURCE";
  String ADD_LEAD_DISTRIBUTE = "ADD_LEAD_DISTRIBUTE";
  String GET_ALL_LEAD_DISTRIBUTE = "GET_ALL_LEAD_DISTRIBUTE";
  String GET_LEAD_DISTRIBUTE_BY_ID = "GET_LEAD_DISTRIBUTE_BY_ID";
  String UPDATE_STATUS_LEAD_DISTRIBUTE = "UPDATE_STATUS_LEAD_DISTRIBUTE";
  String DELETE_DISTRIBUTE = "DELETE_DISTRIBUTE";
  String UPDATE_DISTRIBUTE = "UPDATE_DISTRIBUTE";
  String DOWNLOAD_LEAD = "DOWNLOAD_LEAD";
  String IMPORT_LEAD = "IMPORT_LEAD";
  String DOWNLOAD_PATTERN = "DOWNLOAD_PATTERN";
  String LEAD_DISTRIBUTE = "LEAD_DISTRIBUTE";

  String GET_ALL_PROJECT = "GET_ALL_PROJECT";
  String ADD_PROJECT = "ADD_PROJECT";
  String UPDATE_STATUS_PROJECT = "UPDATE_STATUS_PROJECT";
  String UPDATE_PROJECT = "UPDATE_PROJECT";
  String GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
  String GET_DISTRIBUTE_API_ACTIVE_AND_NOT_EXIST = "GET_DISTRIBUTE_API_ACTIVE_AND_NOT_EXIST";

  String ADD_CAMPAIGN = "ADD_CAMPAIGN";
  String GET_ALL_CAMPAIGN = "GET_ALL_CAMPAIGN";
  String UPDATE_CAMPAIGN = "UPDATE_CAMPAIGN";
  String GET_CAMPAIGN_DETAIL = "GET_CAMPAIGN_DETAIL";
  String UPDATE_STATUS_CAMPAIGN = "UPDATE_STATUS_CAMPAIGN";
  String GET_CAMPAIGNS_CODE = "GET_CAMPAIGNS_CODE";

  String GET_ALL_LEAD = "GET_ALL_LEAD";
  String GET_LEAD_BY_ID = "GET_LEAD_BY_ID";
  String GET_HISTORY_LEAD = "GET_HISTORY_LEAD";
  String GET_ALL_STATUS_LEAD = "GET_ALL_STATUS_LEAD";
  String GET_LIST_LEAS_STATUS = "GET_LIST_LEAS_STATUS";

  String ADD_OFFER = "ADD_OFFER";
  String GET_OFFER_BY_ID = "GET_OFFER_BY_ID";
  String DELETE_OFFER = "DELETE_OFFER";
  String UPDATE_OFFER = "UPDATE_OFFER";
  String GET_ALL_OFFER = "GET_ALL_OFFER";

  String ADD_FILTER = "ADD_FILTER";
  String GET_FILTER_BY_ID = "GET_FILTER_BY_ID";
  String DELETE_FILTER = "DELETE_FILTER";
  String UPDATE_FILTER = "UPDATE_FILTER";
  String GET_ALL_FILTER = "GET_ALL_FILTER";

  String ADD_SCHEDULE = "ADD_SCHEDULE";
  String GET_SCHEDULE_BY_ID = "GET_SCHEDULE_BY_ID";
  String DELETE_SCHEDULE = "DELETE_SCHEDULE";
  String UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
  String UPDATE_SCHEDULE_STATUS = "UPDATE_SCHEDULE_STATUS";
  String GET_LIST_SCHEDULE_IN_CAMPAIGN = "GET_LIST_SCHEDULE_IN_CAMPAIGN";

}
